import type { Instrument } from '@folio/shared';
// Identity metadata verified through the recorded provider probes; no provider prices are seeded here.
// Sector remains Unknown until an authorized metadata source verifies it.
export const instrumentMaster: readonly Instrument[] = [
  {
    id: 'TCS:NSE',
    symbol: 'TCS',
    name: 'Tata Consultancy Services Limited',
    exchange: 'NSE',
    currency: 'INR',
    assetClass: 'equity',
    sector: 'Unknown',
    provider: 'yahoo',
    providerId: 'TCS.NS',
    metadataSource: 'Yahoo chart identity audit 2026-10-04; TCS.NS/INR/NSE',
  },
  {
    id: 'RELIANCE:BSE',
    symbol: 'RELIANCE',
    name: 'Reliance Industries Limited',
    exchange: 'BSE',
    currency: 'INR',
    assetClass: 'equity',
    sector: 'Unknown',
    provider: 'yahoo',
    providerId: 'RELIANCE.BO',
    metadataSource: 'Yahoo chart identity audit 2026-10-04; RELIANCE.BO/INR/BSE',
  },
  {
    id: 'AAPL:US',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    exchange: 'US',
    currency: 'USD',
    assetClass: 'equity',
    sector: 'Unknown',
    provider: 'yahoo',
    providerId: 'AAPL',
    metadataSource: 'Yahoo chart identity audit 2026-10-04; AAPL/USD/NMS',
  },
  {
    id: 'VTI:US',
    symbol: 'VTI',
    name: 'Vanguard Morningstar Total Stock Market ETF',
    exchange: 'US',
    currency: 'USD',
    assetClass: 'etf',
    sector: 'Unknown',
    provider: 'yahoo',
    providerId: 'VTI',
    metadataSource: 'Yahoo chart identity audit 2026-10-04; VTI/USD/NYSEArca/ETF; name as returned',
  },
  {
    id: 'BTC:CRYPTO',
    symbol: 'BTC',
    name: 'Bitcoin',
    exchange: 'CRYPTO',
    currency: 'USD',
    assetClass: 'crypto',
    sector: 'Unknown',
    provider: 'coingecko',
    providerId: 'bitcoin',
    metadataSource: 'CoinGecko coins/list identity audit 2026-10-04',
  },
  {
    id: 'ETH:CRYPTO',
    symbol: 'ETH',
    name: 'Ethereum',
    exchange: 'CRYPTO',
    currency: 'USD',
    assetClass: 'crypto',
    sector: 'Unknown',
    provider: 'coingecko',
    providerId: 'ethereum',
    metadataSource: 'CoinGecko coins/list identity audit 2026-10-04',
  },
];
